# Cache key for CircleCI. We want to invalidate the cache whenever the Yarn lock file changes.
var_1: &cache_key angular-clang-format-{{ checksum "yarn.lock" }}
var_2: &default_docker_image circleci/node:10.12

# Settings common to each job
var_3: &job_defaults
  working_directory: ~/clang-format
  docker:
  - image: *default_docker_image

var_4: &save_cache
  save_cache:
    key: *cache_key
    paths:
    - "node_modules/"

jobs:
  build:
    <<: *job_defaults
    steps:
    - checkout
    - restore_cache:
        key: *cache_key
    - run: yarn install --frozen-lockfile --non-interactive
    - run: yarn test
    - *save_cache
